---
# Main tasks file for Python development environment
# This role handles Python installation and development tools

- name: Include Python installation tasks
  ansible.builtin.include_tasks: python.yml
  tags: [python, install]

- name: Include Poetry installation tasks
  ansible.builtin.include_tasks: poetry.yml
  tags: [poetry, install]
  when: install_poetry | default(true) | bool

- name: Include pyenv installation tasks
  ansible.builtin.include_tasks: pyenv.yml
  tags: [pyenv, install]
  when: install_pyenv | default(false) | bool and ansible_facts['os_family'] != 'Windows'
