---
- name: Ensure Python is installed (Linux)
  ansible.builtin.package:
    name: "python{{ python_version | default('3') }}"
    state: present
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Ensure Python is installed (Windows)
  ansible.windows.win_chocolatey:
    name: python
    state: present
  when: ansible_facts['os_family'] == 'Windows'

- name: Install dev tools
  ansible.builtin.pip:
    name: "{{ dev_python_tools | default(['black','flake8','pytest']) }}"
    state: present
  when: ansible_facts['os_family'] in ['Debian', 'RedHat', 'MacOSX']
