---
- name: Ensure Node.js is installed (Linux)
levonk.common.package:
    name: nodejs
    state: latest
  when:
    - dev_js_install_nodejs | default(true)
    - ansible_facts['os_family'] in ['Debian', 'RedHat', 'Ubuntu']

- name: Ensure npm is installed (Linux)
  levonk.common.package:
    name: npm
    state: latest
  when:
    - dev_js_install_nodejs | default(true)
    - ansible_facts['os_family'] in ['Debian', 'RedHat', 'Ubuntu']

- name: Ensure Node.js is installed (Windows)
  levonk.common:
    name: nodejs
    state: latest
  when:
    - dev_js_install_nodejs | default(true)
    - ansible_facts['os_family'] == 'Windows'
