---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all

platforms:
  - name: ubuntu-22.04
    driver:
      box: bento/ubuntu-22.04

suites:
  - name: default
    provisioner:
      playbook: tests/kitchen/test.yml
