---
- name: Verify baseline compliance controls
  hosts: all
  gather_facts: false
  tasks:
    - name: Check password authentication is disabled (Linux)
      ansible.builtin.command: grep '^PasswordAuthentication no' /etc/ssh/sshd_config
      register: passwd_auth
      failed_when: passwd_auth.rc != 0
      changed_when: false
      when: ansible_facts['os_family'] in ['Debian', 'RedHat']

    - name: Check firewall is enabled (Linux/macOS)
      ansible.builtin.command: |
        ufw status | grep -q active || /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate | grep -q enabled
      register: fw_status
      failed_when: fw_status.rc != 0
      changed_when: false
      when: ansible_facts['os_family'] in ['Debian', 'Darwin']

    - name: Check Windows firewall (Windows)
      ansible.windows.win_firewall:
        state: enabled
      check_mode: yes
      when: ansible_facts['os_family'] == 'Windows'

    - name: Verify etckeeper package is installed
      ansible.builtin.package:
        name: etckeeper
        state: present
      check_mode: yes

    - name: Verify etckeeper git repository exists
      ansible.builtin.stat:
        path: /etc/.git
      register: etckeeper_git_dir

    - name: Fail if etckeeper git repository does not exist
      ansible.builtin.fail:
        msg: "Etckeeper git repository was not found at /etc/.git"
      when: not etckeeper_git_dir.stat.exists

    - name: Verify etckeeper is configured for git
      ansible.builtin.lineinfile:
        path: /etc/etckeeper/etckeeper.conf
        line: 'VCS="git"'
        state: present
      check_mode: yes

    - name: Check for the automated commit message in etckeeper log
      ansible.builtin.command:
        cmd: git log --grep="Ansible committed configuration changes" --oneline
        chdir: /etc
      register: etckeeper_commit_log
      changed_when: false

    - name: Fail if the automated commit was not found
      ansible.builtin.fail:
        msg: "The automated etckeeper commit was not found in the git log."
      when: etckeeper_commit_log.stdout | length == 0
