---
driver:
  name: docker

platforms:
  - name: debian-graphical
    image: "geerlingguy/docker-debian11-ansible:latest"
    privileged: true
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      container: docker

provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml

verifier:
  name: ansible
