---
- name: Ensure shell for local user is installed
  levonk.common.package:
    name: "{{ local_user_shell | default('/bin/bash') | basename }}"
    state: latest
  when: local_user_shell is defined and local_user_shell not in ['/usr/sbin/nologin', '/sbin/nologin', '/bin/false']
  tags:
    - local_user
    - shell

- name: Ensure local user exists
  ansible.builtin.user:
    name: "{{ local_user_name }}"
    shell: "{{ local_user_shell | default('/bin/bash') }}"
    groups: "{{ local_user_groups | default([]) }}"
    state: present

- name: Set authorized SSH keys
  ansible.posix.authorized_key:
    user: "{{ local_user_name }}"
    key: "{{ item }}"
  loop: "{{ local_user_ssh_keys | default([]) }}"
  when: local_user_ssh_keys is defined and local_user_ssh_keys|length > 0
