---
# Ensure SSH client and server are installed on Windows

- name: Ensure OpenSSH Client/Server installed via levonk.common.package (Windows)
  levonk.common.package:
    name:
      - openssh.client
      - openssh.server
      - openssh
    state: latest
  tags:
    - vibeops
    - tools
    - ssh
    - openssh


# Change SSHD to listen on port 7722
- name: Set SSHD to listen on port 7722 (Windows)
  ansible.windows.win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    regexp: '^#?Port '
    line: 'Port 7722'
    state: present
    backup: yes
  when: ansible_os_family == 'Windows'
  notify: Restart sshd

# Open port 7722/tcp in the system firewall for SSH access
- name: Open SSH port in firewall (7722/tcp)
  ansible.builtin.include_role:
    name: levonk.common.open_firewall_port
  vars:
    open_firewall_port_port: 7722
    open_firewall_port_proto: tcp
    open_firewall_port_service: "ssh"
  tags:
    - firewall
    - ssh
