---
# tasks file for installing Vagrant securely and idempotently
# Tags: [vagrant, tools, install]
#
# Copyright (c) 2025 the person whose account is https://github.com/levonk. Licensed under the GNU AGPL-3.0 License.
# See LICENSE file in the project root for full license information.
#
# This file ensures Vagrant and essential plugins are installed securely and idempotently across supported OSes.
# The intention is to provide a robust, portable, and secure local development experience for all users.


- name: Check if Vagrant is already installed
  ansible.builtin.command: vagrant --version
  register: vagrant_version
  ignore_errors: yes
  changed_when: false
  tags:
    - vagrant
    - tools

- name: Try to install Vagrant using levonk.common.package (Debian)
  levonk.common.package:
    name: vagrant
    state: latest
  register: vagrant_pkg_result
  when:
    - ansible_os_family == 'Debian'
    - vagrant_version.rc != 0
  ignore_errors: yes
  tags:
    - vagrant
    - tools
    - package
  # Intention: Use package manager for Vagrant if available for security, idempotency, and system integration.

- name: Install dependencies for Vagrant (cross-platform)
  levonk.common.package:
    name:
      - libvirt-daemon-system
      - libvirt-clients
      - qemu-kvm
      - ruby
    state: latest
  tags:
    - vagrant
    - tools

- name: Download Vagrant installer securely (Debian fallback)
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1_{{ ansible_system | lower }}_amd64.deb"
    dest: "/tmp/vagrant_latest.deb"
    mode: '0644'
    checksum: "sha256:{{ lookup('url', 'https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1_SHA256SUMS') | regex_search('vagrant_2.4.1_{{ ansible_system | lower }}_amd64.deb.*([a-f0-9]{64})', '\1') }}"
  when:
    - ansible_os_family == 'Debian'
    - vagrant_version.rc != 0
    - vagrant_pkg_result is failed or vagrant_pkg_result is skipped
  tags:
    - vagrant
    - tools
    - fallback
  # Intention: Download Vagrant securely only if package manager install is unavailable or fails.

- name: Vet Vagrant installer script (security)
  include_role:
    name: levonk.common.vet_script_installer
  vars:
    script_path: "/tmp/vagrant_latest.deb"
  when:
    - ansible_os_family == 'Debian'
    - vagrant_version.rc != 0
    - vagrant_pkg_result is failed or vagrant_pkg_result is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Install Vagrant (Debian fallback)
  ansible.builtin.apt:
    deb: /tmp/vagrant_latest.deb
  when:
    - ansible_os_family == 'Debian'
    - vagrant_version.rc != 0
    - vagrant_pkg_result is failed or vagrant_pkg_result is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Ensure Vagrant is in PATH
  ansible.builtin.command: vagrant --version
  register: vagrant_path_check
  changed_when: false
  tags:
    - vagrant
    - tools

- name: Ensure vagrant-vbguest plugin is installed (host)
  community.general.vagrant_plugin:
    name: vagrant-vbguest
    state: present
  become: false
  tags:
    - vagrant
    - vagrant_plugin
    - vbguest
    - tools
  # Intention: Guarantee that the vagrant-vbguest plugin is always present on the host system.
  # This enables automatic VirtualBox Guest Additions management for Vagrant VMs, improving compatibility and user experience.

- name: Try to install Vagrant using levonk.common.package (Windows)
  levonk.common.package:
    name: vagrant
    state: latest
  register: vagrant_pkg_result_win
  when:
    - ansible_os_family == 'Windows'
    - vagrant_version.rc != 0
  ignore_errors: yes
  tags:
    - vagrant
    - tools
    - package

- name: Download Vagrant installer for Windows (fallback)
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1_windows_amd64.msi"
    dest: "%TEMP%/vagrant_latest.msi"
    mode: '0644'
  when:
    - ansible_os_family == 'Windows'
    - vagrant_version.rc != 0
    - vagrant_pkg_result_win is failed or vagrant_pkg_result_win is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Vet Vagrant installer script (Windows)
  include_role:
    name: levonk.common.vet_script_installer
  vars:
    script_path: "%TEMP%/vagrant_latest.msi"
  when:
    - ansible_os_family == 'Windows'
    - vagrant_version.rc != 0
    - vagrant_pkg_result_win is failed or vagrant_pkg_result_win is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Install Vagrant (Windows fallback)
  ansible.windows.win_package:
    path: "%TEMP%/vagrant_latest.msi"
    state: present
  when:
    - ansible_os_family == 'Windows'
    - vagrant_version.rc != 0
    - vagrant_pkg_result_win is failed or vagrant_pkg_result_win is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Try to install Vagrant using levonk.common.package (macOS)
  levonk.common.package:
    name: vagrant
    state: present
  register: vagrant_pkg_result_mac
  when:
    - ansible_os_family == 'Darwin'
    - vagrant_version.rc != 0
  ignore_errors: yes
  tags:
    - vagrant
    - tools
    - package

- name: Download Vagrant installer for macOS (fallback)
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vagrant/2.4.1/vagrant_2.4.1_x86_64.dmg"
    dest: "/tmp/vagrant_latest.dmg"
    mode: '0644'
  when:
    - ansible_os_family == 'Darwin'
    - vagrant_version.rc != 0
    - vagrant_pkg_result_mac is failed or vagrant_pkg_result_mac is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Vet Vagrant installer script (macOS)
  include_role:
    name: levonk.common.vet_script_installer
  vars:
    script_path: "/tmp/vagrant_latest.dmg"
  when:
    - ansible_os_family == 'Darwin'
    - vagrant_version.rc != 0
    - vagrant_pkg_result_mac is failed or vagrant_pkg_result_mac is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Install Vagrant (macOS fallback)
  ansible.builtin.command: hdiutil attach /tmp/vagrant_latest.dmg && sudo installer -pkg /Volumes/Vagrant/Vagrant.pkg -target /
  args:
    warn: false
  when:
    - ansible_os_family == 'Darwin'
    - vagrant_version.rc != 0
    - vagrant_pkg_result_mac is failed or vagrant_pkg_result_mac is skipped
  tags:
    - vagrant
    - tools
    - fallback

- name: Vagrant install not implemented for this OS
  ansible.builtin.fail:
    msg: "Vagrant installation is not implemented for this OS family ({{ ansible_os_family }}). Please contribute support."
  when:
    - ansible_os_family not in ['Debian', 'Windows', 'Darwin']
  tags:
    - vagrant
    - tools
