---
- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_stat

- name: Install Homebrew using vetted installer
  ansible.builtin.include_role:
    name: levonk.common.vet_script_installer
  vars:
    vet_script_url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    vet_script_dest: "/tmp/homebrew-install.sh"
    vet_script_args: ""
  when: not homebrew_stat.stat.exists

- name: Install essential packages on macOS
  community.general.homebrew:
    name: "{{ base_system_packages }}"
    state: present
