---
# tasks file for base_system

- name: Include Debian/Ubuntu tasks
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Include macOS tasks
  include_tasks: macos.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_facts['os_family'] == 'Windows'

- name: Install JetBrains Mono Nerd Font (all OS)
  include_tasks: fonts.yml
