# Time and timezone configuration
- name: Set timezone (Linux/Windows)
  timezone:
    name: "{{ timezone }}"
  when: ansible_os_family != 'Darwin'
  tags: ['system', 'timezone']

- name: Set timezone (macOS)
  command: systemsetup -settimezone "{{ timezone }}"
  when: ansible_os_family == 'Darwin'
  tags: ['system', 'timezone', 'macos']

# NTP and time sync (see original for full details)
# ... (remaining NTP logic can be added as needed)
