---
- name: Ensure backup directory exists
  win_file:
    path: C:\\backup
    state: directory

- name: Back up HKLM registry hive
  win_command: reg export HKLM C:\\backup\\HKLM.reg /y
  args:
    creates: C:\\backup\\HKLM.reg

- name: Back up HKCU registry hive
  win_command: reg export HKCU C:\\backup\\HKCU.reg /y
  args:
    creates: C:\\backup\\HKCU.reg

- name: Back up HKU registry hive
  win_command: reg export HKU C:\\backup\\HKU.reg /y
  args:
    creates: C:\\backup\\HKU.reg

- name: Back up HKCR registry hive
  win_command: reg export HKCR C:\\backup\\HKCR.reg /y
  args:
    creates: C:\\backup\\HKCR.reg

- name: Back up HKCC registry hive
  win_command: reg export HKCC C:\\backup\\HKCC.reg /y
  args:
    creates: C:\\backup\\HKCC.reg

- name: Install Chocolatey if not present
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  args:
    creates: C:\\ProgramData\\chocolatey\\bin\\choco.exe

- name: Install essential packages on Windows
  win_chocolatey:
    name: "{{ base_system_packages }}"
    state: present
