---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all

platforms:
  - name: debian-11
    driver:
      box: debian/bullseye64

suites:
  - name: default
    provisioner:
      playbook: tests/integration/default.yml
