---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
verifier:
  name: ansible
scenario:
  name: default