---
namespace: levonk
name: hardened
version: 1.1.0
readme: README.md
authors:
  - Levon Kachadourian
description: Levonk hardened collection
license:
  - MIT
tags:
  - levonk
  - ansible
  - collection
repository: https://github.com/levonk/levonk-ansible-galaxy
documentation: https://github.com/levonk/levonk-ansible-galaxy
homepage: https://github.com/levonk/levonk-ansible-galaxy
issues: https://github.com/levonk/levonk-ansible-galaxy/issues
