# SPDX-License-Identifier: AGPL-3.0-only
namespace: levonk
name: hardened
version: 1.0.0
readme: README.md
authors:
  - levonk <v3l8dud3@lkara.com>
description: Security hardening roles for cross-platform hosts (Linux, macOS, Windows) with compliance mapping.
license:
  - AGPL-3.0-only
tags:
  - hardening
  - compliance
  - security
  - cis
  - nist
  - crossplatform
dependencies: {}
repository: http://github.com/levonk/levonk-ansible-galaxy
documentation: http://docs.example.com
homepage: http://github.com/levonk/levonk-ansible-galaxy
issues: http://github.com/levonk/levonk-ansible-galaxy/issue/tracker
