---
# Docker Optimization Tools
# Handles installation of tools for optimizing Docker images and containers

- name: Set optimization tools version variables
  ansible.builtin.set_fact:
    hadolint_version: "{{ hadolint_version | default('v2.12.0') }}"
    docker_slim_version: "{{ docker_slim_version | default('1.40.3') }}"
    docker_compose_version: "{{ docker_compose_version | default('v2.23.0') }}"

# Hadolint - Dockerfile linter
- name: Install Hadolint
  levonk.common.package:
    name: hadolint
    state: latest
  tags: [docker, optimize, hadolint]

# Docker Slim - Minify and Secure Docker containers
- name: Install Docker Slim
  levonk.common.package:
    name: docker-slim
    state: latest
  tags: [docker, optimize, docker-slim]

# Verify optimization tools installation
- name: Verify optimization tools installation
  ansible.builtin.command: "{{ item }} --version"
  with_items:
    - hadolint
    - docker-slim
  register: optimize_tools_check
  changed_when: false
  ignore_errors: yes
  tags: [docker, optimize]
