---
# tasks file for levonk.user_setup.thick-shell - bat

- name: Install bat via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - bat
    state: latest
  tags:
    - thick-shell
    - tools
    - bat
    - syntax-highlighting

- name: Install bat on macOS via Homebrew
  community.general.homebrew:
    name: bat
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - thick-shell
    - tools
    - bat
    - syntax-highlighting

- name: Verify bat installation
  ansible.builtin.command:
    cmd: bat --version
  register: bat_version
  changed_when: false
  failed_when: false
  tags:
    - thick-shell
    - tools
    - bat
    - verify

- name: Display bat version
  ansible.builtin.debug:
    msg: "bat version: {{ bat_version.stdout }}"
  when: bat_version.rc == 0
  tags:
    - thick-shell
    - tools
    - bat
    - verify
