---
# tasks file for levonk.user_setup.thick-shell - ripgrep

- name: Install ripgrep via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - ripgrep
    state: latest
  tags:
    - thick-shell
    - tools
    - ripgrep
    - search

- name: Verify ripgrep installation
  ansible.builtin.command:
    cmd: rg --version
  register: ripgrep_version
  changed_when: false
  failed_when: false
  tags:
    - thick-shell
    - tools
    - ripgrep
    - verify

- name: Display ripgrep version
  ansible.builtin.debug:
    msg: "ripgrep version: {{ ripgrep_version.stdout }}"
  when: ripgrep_version.rc == 0
  tags:
    - thick-shell
    - tools
    - ripgrep
    - verify
