---
- include_tasks: ../nix_check.yml

- name: Initialize Nix result
  set_fact:
    _levonk_nix_install_success: false

- name: Attempt install with Nix
  block:
    - name: Install package with Nix
      command: "nix-env -iA nixpkgs.{{ package_name }}"
      environment:
        PATH: "/nix/var/nix/profiles/default/bin:/root/.nix-profile/bin:{{ ansible_env.PATH }}"
        NIX_PATH: "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs:/nix/var/nix/profiles/per-user/{{ ansible_user_id }}/channels/nixpkgs"
      register: _nix_install_cmd
      ignore_errors: true
      changed_when: "'installing' in _nix_install_cmd.stderr"

    - name: Record Nix success
      set_fact:
        _levonk_nix_install_success: true
      when: _nix_install_cmd.rc == 0
  when: nix_available | default(false)

- name: Fallback to native package manager
  include_tasks: linux_native.yml
  when: not _levonk_nix_install_success
