---
galaxy_info:
  author: levonk
  description: Installs WSL2 and a specified Linux distribution on Windows.
  company: levonk
  license: Copyright (c) 2025, levonk

  min_ansible_version: '2.9'

  platforms:
    - name: Windows
      versions:
        - all

  galaxy_tags:
    - wsl
    - wsl2
    - debian
    - windows

dependencies: []
