---
- name: Converge
  hosts: all
  become: true
  vars:
    timezone: "America/New_York"
    ntp_servers:
      - "time.google.com"
      - "time.cloudflare.com"
  roles:
    - role: ../../base_system
# All macOS logic is now handled by package-managers/homebrew.yml and base_packages.yml. No reference to macos.yml remains.
