---
# Baseline hardening: OS dispatcher

- name: Include Linux baseline tasks
  import_tasks: linux.yml
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Include macOS baseline tasks
  import_tasks: macos.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Include Windows baseline tasks
  import_tasks: windows.yml
  when: ansible_facts['os_family'] == 'Windows'
