---
# Cloudflare WARP client installation and configuration
# https://developers.cloudflare.com/warp-client/

---
# Cloudflare WARP client installation and configuration
# https://developers.cloudflare.com/warp-client/

- name: Block for Debian-based systems
  tags:
    - security
    - networking
    - warp
  block:
    - name: Install prerequisites for WARP
      levonk.common.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
      become: true
      tags:
        - harden_baseline
        - linux
        - warp
    # TODO: Abstract repo/key management into levonk.common if possible
    - name: Add Cloudflare GPG key
      apt_key:
        url: https://pkg.cloudflareclient.com/pubkey.gpg
        state: present
      become: true
    - name: Add Cloudflare WARP repository
      apt_repository:
        repo: "deb [arch=amd64] https://pkg.cloudflareclient.com/ {{ ansible_distribution_release }} main"
        state: present
        filename: cloudflare-warp
      become: true
    - name: Install Cloudflare WARP CLI
      levonk.common.package:
        name: cloudflare-warp
        state: latest
      become: true
      tags:
        - harden_baseline
        - linux
        - warp
    - name: Ensure WARP service is enabled and started
      service:
        name: warp-svc
        state: started
        enabled: yes
      become: true
    - name: Check if WARP is already registered
      command: warp-cli --accept-tos status
      register: warp_status
      changed_when: false
      failed_when: warp_status.rc != 0 and 'Missing registration' not in warp_status.stderr
    - name: Register WARP client (if not already registered)
      command: warp-cli --accept-tos register
      when: '"Missing registration" in warp_status.stderr'
    - name: Enable WARP mode (if registered)
      command: warp-cli --accept-tos set-mode warp
      when: '"Missing registration" not in warp_status.stderr'
    - name: Connect to WARP
      command: warp-cli --accept-tos connect
  when:
    - ansible_os_family == 'Debian'
    - harden_baseline_install_warp_cli | default(true)

- name: Block for Windows systems
  tags:
    - security
    - networking
    - warp
  block:
    - name: Install Cloudflare WARP on Windows
      levonk.common.package:
        name: cloudflare-warp
        state: latest
      become: true
      tags:
        - harden_baseline
        - windows
        - warp
    - name: Verify WARP CLI installation on Windows
      win_command: warp-cli --version
      register: warp_version_windows
      changed_when: false
      failed_when: warp_version_windows.rc != 0
    - name: Display WARP version on Windows
      debug:
        msg: "WARP CLI installed: {{ warp_version_windows.stdout }}"
  when:
    - ansible_os_family == 'Windows'
    - harden_baseline_install_warp_cli | default(true)

- name: Block for macOS systems
  tags:
    - security
    - networking
    - warp
  block:
    - name: Install Cloudflare WARP on macOS
      levonk.common.package:
        name: cloudflare-warp
        state: latest
      become: true
      tags:
        - harden_baseline
        - macos
        - warp
    - name: Verify WARP CLI installation on macOS
      command: warp-cli --version
      register: warp_version_macos
      changed_when: false
      failed_when: warp_version_macos.rc != 0
    - name: Display WARP version on macOS
      debug:
        msg: "WARP CLI installed: {{ warp_version_macos.stdout }}"
  when:
    - ansible_os_family == 'Darwin'
    - harden_baseline_install_warp_cli | default(true)

# GUI installation (requires graphical tag)
- name: Install WARP GUI on Windows
  debug:
    msg: "WARP GUI installation should use levonk.common.package when available."
  when:
    - ansible_os_family == 'Windows'
    - harden_baseline_install_warp_gui | default(false)
    - "'graphical' in ansible_run_tags"
  tags:
    - security
    - networking
    - warp
    - graphical

- name: Install WARP GUI on macOS (already included with cask)
  debug:
    msg: "WARP GUI is included with the macOS cask installation"
  when:
    - ansible_os_family == 'Darwin'
    - harden_baseline_install_warp_gui | default(false)
    - "'graphical' in ansible_run_tags"
  tags:
    - security
    - networking
    - warp
    - graphical

- name: Install WARP GUI on Linux (if available)
  debug:
    msg: "WARP GUI for Linux is not officially available. CLI version installed."
  when:
    - ansible_os_family in ['Debian', 'RedHat']
    - harden_baseline_install_warp_gui | default(false)
    - "'graphical' in ansible_run_tags"
  tags:
    - security
    - networking
    - warp
    - graphical
