---
# Harden Baseline: Windows baseline hardening tasks

- name: Ensure firewall is enabled
  ansible.windows.win_firewall:
    state: enabled
  tags:
    - harden_baseline
    - windows
    - security
    - firewall

# Disable Guest account for baseline security
- name: Ensure Guest account is disabled
  ansible.windows.win_user:
    name: Guest
    account_disabled: yes
  tags:
    - harden_baseline
    - windows
    - security
    - guest

# Enable audit policy for logon events (baseline)
- name: Set audit policy for logon events
  ansible.windows.win_audit_policy_system:
    category: Logon/Logoff
    subcategory: Logon
    audit_type: success, failure
  tags:
    - harden_baseline
    - windows
    - security
    - audit
