---
# Linux advanced compliance (CIS/NIST/2FA/MFA, kernel hardening)

- name: Enforce 2FA/MFA for privileged access (PAM - manual/integrated)
  ansible.builtin.debug:
    msg: "Ensure PAM 2FA/MFA is enabled for privileged users (e.g., pam_google_authenticator, pam_yubico). See documentation for integration steps."

- name: Harden kernel parameters (sysctl)
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
    reload: yes
  loop:
    - { key: 'kernel.randomize_va_space', value: '2' }
    - { key: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { key: 'net.ipv4.conf.default.rp_filter', value: '1' }
    - { key: 'net.ipv4.tcp_syncookies', value: '1' }
    - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
    - { key: 'net.ipv4.conf.default.accept_source_route', value: '0' }
    - { key: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
    - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
    - { key: 'net.ipv4.conf.all.log_martians', value: '1' }
    - { key: 'net.ipv4.conf.default.log_martians', value: '1' }

- name: CIS/NIST mapping documentation
  ansible.builtin.debug:
    msg: "See README.md for full CIS/NIST mapping."
