---
# Install JetBrains Mono Nerd Font on all platforms

- name: Ensure font dependencies (Debian)
  include_role:
    name: levonk.common.package
  vars:
    name:
      - unzip
      - fontconfig
    state: latest
  when: ansible_os_family == 'Debian'
  tags: ['fonts', 'dependencies', 'debian']

- name: Install JetBrains Mono Nerd Font (macOS, Homebrew Cask)
  include_role:
    name: levonk.common.package
  vars:
    name: font-jetbrains-mono-nerd-font
    cask: true
    state: latest
  when: ansible_os_family == 'Darwin'
  tags: ['fonts', 'jetbrains', 'macos']
# TODO: Compliance - Ensure font use is reviewed for compliance

- name: Install JetBrains Mono Nerd Font (Windows, Winget)
  include_role:
    name: levonk.common.package
  vars:
    name: Ryanoasis.JetBrainsMonoNerdFont
    provider: winget
    state: latest
  when: ansible_os_family == 'Windows'
  tags: ['fonts', 'jetbrains', 'windows', 'winget']
# TODO: Compliance - Ensure font use is reviewed for compliance

- name: Install JetBrains Mono Nerd Font (Debian fallback/manual)
  when: ansible_os_family == 'Debian'
  block:
    - name: Download and install JetBrains Mono Nerd Font manually (if not in package manager)
      ansible.builtin.get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip"
        dest: "/tmp/JetBrainsMono.zip"
        mode: '0644'
      register: font_download
    - name: Unzip font to system fonts directory
      ansible.builtin.unarchive:
        src: "/tmp/JetBrainsMono.zip"
        dest: "/usr/local/share/fonts/"
        remote_src: yes
      when: font_download is changed
    - name: Rebuild font cache
      ansible.builtin.command: fc-cache -f -v
      changed_when: false

    - name: Get latest JetBrains Mono Nerd Font release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest"
        return_content: true
      register: nerd_font_latest_release

    - name: Find JetBrainsMono.zip asset URL
      ansible.builtin.set_fact:
        jetbrainsmono_zip_url: "{{ (nerd_font_latest_release.json.assets | selectattr('name', 'equalto', 'JetBrainsMono.zip') | list | first).browser_download_url }}"

    - name: Create fonts directory
      ansible.builtin.file:
        path: "~/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Download and unzip JetBrains Mono Nerd Font
      ansible.builtin.unarchive:
        src: "{{ jetbrainsmono_zip_url }}"
        dest: "~/.local/share/fonts"
        remote_src: true
      when: jetbrainsmono_zip_url is defined

    - name: Rebuild font cache
      ansible.builtin.command:
        cmd: fc-cache -fv
      changed_when: false
