---
# APK (Alpine) package install logic for levonk.common.package
# TODO: Compliance - Add compliance test for apk licensing

- name: APK: Ensure apk cache is updated if needed
  command: apk update
  when: update_cache | default(false)
  register: apk_update
  changed_when: false
  ignore_errors: true

- name: APK: Install/upgrade package
  command: apk add --no-cache {{ package_name }}
  register: apk_result
  changed_when: apk_result.rc == 0 and 'installed' in apk_result.stdout
  ignore_errors: true

- name: APK: Verify package installed
  command: apk info -e {{ package_name }}
  register: apk_verify
  changed_when: false
  ignore_errors: true

- name: APK: Fail if not installed
  fail:
    msg: "Failed to install {{ package_name }} with apk."
  when: apk_result is not defined or apk_result.rc != 0 or (apk_verify is defined and apk_verify.rc != 0)

- name: APK: Log package installation result
  ansible.builtin.debug:
    msg: "Package {{ package_name }} installed successfully with result: {{ apk_result }}"
    warn: false

- name: APK: Return result
  set_fact:
    levonk_package_result: "{{ apk_result }}"
