---
- name: Install TypeScript globally (Linux/macOS)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - typescript
  when:
    - dev_js_install_typescript | default(true)
    - ansible_facts['os_family'] != 'Windows'

- name: Install TypeScript globally (Windows)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - typescript
  when:
    - dev_js_install_typescript | default(true)
    - ansible_facts['os_family'] == 'Windows'

- name: Install Vite globally (Linux/macOS)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - vite
  when:
    - dev_js_install_vite | default(true)
    - ansible_facts['os_family'] != 'Windows'

- name: Install Vite globally (Windows)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - vite
  when:
    - dev_js_install_vite | default(true)
    - ansible_facts['os_family'] == 'Windows'

- name: Install create-react-app globally (Linux/macOS)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - create-react-app
  when:
    - dev_js_install_create_react_app | default(true)
    - ansible_facts['os_family'] != 'Windows'

- name: Install create-react-app globally (Windows)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - create-react-app
  when:
    - dev_js_install_create_react_app | default(true)
    - ansible_facts['os_family'] == 'Windows'
