---
- name: Install Prettier globally (Linux/macOS)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - prettier
  when:
    - dev_js_install_prettier | default(true)
    - ansible_facts['os_family'] != 'Windows'

- name: Install Prettier globally (Windows)
  include_role:
    name: levonk.common.node-pm
    tasks_from: install_global_packages
  vars:
    npm_packages:
      - prettier
  when:
    - dev_js_install_prettier | default(true)
    - ansible_facts['os_family'] == 'Windows'
