---
# Main task for thick-shell role (multi-shell support)
- name: Set default shell list if not specified
  set_fact:
    thick_shells: "{{ thick_shells | default(['zsh']) }}"

- name: Ensure zsh stack if requested
  include_tasks: shells/zsh.yml
  when: "'zsh' in thick_shells"

- name: Ensure bash stack if requested
  include_tasks: shells/bash.yml
  when: "'bash' in thick_shells"

- name: Ensure fish stack if requested
  include_tasks: shells/fish.yml
  when: "'fish' in thick_shells"

- name: Always install Oh My Posh + Posh-Git on Windows
  include_tasks: shells/windows_posh.yml
  when: ansible_system == 'Windows'

- name: Install tmux
  include_tasks: tools/tmux.yml
  when: thick_shell_install_tmux 

- name: Install zellij
  include_tasks: tools/zellij.yml
  when: thick_shell_install_zellij 

- name: Install mosh
  include_tasks: tools/mosh.yml
  when: thick_shell_install_mosh 

- name: Install fzf fuzzy finder
  include_tasks: tools/fzf.yml
  when: thick_shell_install_fzf 

- name: Install direnv
  include_tasks: tools/direnv.yml
  when: thick_shell_install_direnv 

- name: Install ripgrep
  include_tasks: tools/ripgrep.yml
  when: thick_shell_install_ripgrep 

- name: Install bat
  include_tasks: tools/bat.yml
  when: thick_shell_install_bat 

- name: Install fd
  include_tasks: tools/fd.yml
  when: thick_shell_install_fd 

- name: Install zoxide
  include_tasks: tools/zoxide.yml
  when: thick_shell_install_zoxide 

- name: Install Neovim
  include_tasks: tools/neovim.yml
  when: thick_shell_install_neovim 
