---
# tasks file for levonk.vibeops.tools - 7-Zip

- name: Install 7-Zip/Keka/p7zip-full via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - 7zip
      - keka
      - p7zip-full
    state: latest
  tags:
    - vibeops
    - tools
    - 7zip
    - keka
    - p7zip

