---
# tasks file for levonk.vibeops.tools

- name: Install Ditto clipboard manager (if graphical is enabled)
  ansible.windows.win_chocolatey:
    name: ditto
    state: present
  when:
    - ansible_facts['os_family'] == 'Windows'
    - graphical | default(false)
  become: yes
