---
# tasks file for levonk.vibeops.tools

- name: Ensure SSH client/server present (Linux/macOS)
  ansible.builtin.include_tasks: ssh_unix.yml
  when: ansible_os_family in ['Debian', 'RedHat', 'Archlinux', 'Darwin']

- name: Ensure SSH client/server present (Windows)
  ansible.builtin.include_tasks: ssh_windows.yml
  when: ansible_os_family == 'Windows'

- name: Install macOS-specific tools
  ansible.builtin.include_tasks: darwin.yml
  when:
    - ansible_os_family == 'Darwin'
    - "'graphical' in ansible_run_tags"

- name: Install Windows-specific tools
  ansible.builtin.include_tasks: windows.yml
  when:
    - ansible_os_family == 'Windows'
    - "'graphical' in ansible_run_tags"

- name: Install OS-specific clipboard managers
  ansible.builtin.include_tasks: clipboard_managers.yml
  when: "'graphical' in ansible_run_tags"

- name: Install OS-specific terminal applications
  ansible.builtin.include_tasks: terminals.yml
  when: "'graphical' in ansible_run_tags"

- name: Install Raycast launcher
  ansible.builtin.include_tasks: raycast.yml
  when: "'graphical' in ansible_run_tags"

- name: Install 7-Zip
  ansible.builtin.include_tasks: 7zip.yml
  when:
    - tools_install_7zip | default(false)
    - "'graphical' in ansible_run_tags"

- name: Install Sublime Text
  ansible.builtin.include_tasks: sublime_text.yml
  when:
    - tools_install_sublime_text | default(false)
    - "'graphical' in ansible_run_tags"

- name: Install git-friendly
  ansible.builtin.include_tasks: git_friendly.yml
  when:
    - tools_install_git_friendly | default(true)

- name: Install Espanso
  ansible.builtin.include_tasks: espanso.yml
  when:
    - tools_install_espanso | default(false)
    - "'graphical' in ansible_run_tags"

- name: Install Speech Tools
  ansible.builtin.include_tasks: speech.yml
  when:
    - tools_install_speech_tools | default(false)
    - "'graphical' in ansible_run_tags"

- name: Install diagram tools (Graphviz, MermaidJS CLI)
  ansible.builtin.include_tasks: diagram-tools.yml

- name: Install m1f tool
  ansible.builtin.include_tasks: m1f.yml
  when: tools_install_m1f | default(false)
