---
# tasks file for levonk.vibeops.tools - Raycast

- name: Install Raycast via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - raycast
    state: latest
  register: raycast_pkg_result
  failed_when: false
  tags:
    - vibeops
    - tools
    - raycast

- name: Fallback: Download Raycast AppImage for Linux if package fails
  when: ansible_os_family == "Debian" and raycast_pkg_result is failed
  block:
    - name: Download Raycast AppImage for Linux
      ansible.builtin.get_url:
        url: https://github.com/ByteAtATime/raycast-linux/releases/download/v0.1.0-alpha/raycast-linux.AppImage
        dest: /usr/local/bin/raycast
        mode: '0755'
      become: true

- name: Install Raycast extension for Homebrew
  ansible.builtin.command: brew install raycast/extensions/raycast-brew
  changed_when: false
  when: ansible_os_family == "Darwin"
