---
# tasks file for levonk.vibeops.tools - Speech Tools

- name: Display note for Windows Voice Access
  ansible.builtin.debug:
    msg: "Windows Voice Access is a built-in feature. Please enable it manually in Settings > Accessibility > Speech."
  when: ansible_os_family == 'Windows'

- name: Display note for macOS Voice Control
  ansible.builtin.debug:
    msg: "macOS Voice Control is a built-in feature. Please enable it manually in System Settings > Accessibility > Voice Control."
  when: ansible_os_family == 'Darwin'

- name: Install Simon speech recognition via levonk.common.package (Debian)
  levonk.common.package:
    name:
      - simon
    state: latest
  when: ansible_os_family == 'Debian'
  tags:
    - vibeops
    - tools
    - speech
    - simon

- name: Note about Simon on other platforms
  ansible.builtin.debug:
    msg: "The Simon speech recognition tool is primarily available for Linux. No package was found for Windows or macOS."
  when: ansible_os_family in ['Windows', 'Darwin']

- name: Install Python-based speech tools
  block:
    - name: Install Whisper CLI
      ansible.builtin.pip:
        name: openai-whisper
        state: present

    - name: Install Dragonfly
      ansible.builtin.pip:
        name: dragonfly2
        state: present

    - name: Note about Python dependencies
      ansible.builtin.debug:
        msg: "Whisper CLI and Dragonfly have been installed using pip. This requires a functional Python environment, which can be set up using the 'levonk.dev_setup.dev-python' role."
