---
# Ensure SSH client and server are installed on Windows

- name: Ensure OpenSSH Client is installed (Windows 10+)
  ansible.windows.win_feature:
    name: OpenSSH.Client
    state: present
  when: ansible_os_family == 'Windows'

- name: Ensure OpenSSH Server is installed (Windows 10+)
  ansible.windows.win_feature:
    name: OpenSSH.Server
    state: present
  when: ansible_os_family == 'Windows'

- block:
    - name: Fallback: Install Win32-OpenSSH via Chocolatey if needed
      ansible.builtin.win_chocolatey:
        name: openssh
        state: present
  when:
    - ansible_os_family == 'Windows'
    - ansible_distribution_major_version is version('10', '<')

# Change SSHD to listen on port 7722
- name: Set SSHD to listen on port 7722 (Windows)
  ansible.windows.win_lineinfile:
    path: C:\ProgramData\ssh\sshd_config
    regexp: '^#?Port '
    line: 'Port 7722'
    state: present
    backup: yes
  when: ansible_os_family == 'Windows'
  notify: Restart sshd

# Open port 7722/tcp in the system firewall for SSH access
- name: Open SSH port in firewall (7722/tcp)
  ansible.builtin.include_role:
    name: levonk.common.open_firewall_port
  vars:
    open_firewall_port_port: 7722
    open_firewall_port_proto: tcp
    open_firewall_port_service: "ssh"
  tags:
    - firewall
    - ssh
