---
# tasks file for levonk.vibeops.comms - Slack

- name: Install Slack on Windows
  ansible.windows.win_winget:
    name: Slack
    id: SlackTechnologies.Slack
    state: present
  when: ansible_os_family == 'Windows'

- name: Install Slack on Debian-based systems
  include_role:
    name: levonk.common.package
  vars:
    package_name: slack-desktop
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Slack on macOS
  community.general.homebrew_cask:
    name: slack
    state: present
  when: ansible_os_family == 'Darwin'
