---
# tasks file for levonk.vibeops.comms - Telegram

- name: Install Telegram on Windows
  ansible.windows.win_winget:
    name: Telegram
    id: Telegram.TelegramDesktop
    state: present
  when: ansible_os_family == 'Windows'

- name: Install Telegram on Debian-based systems
  include_role:
    name: levonk.common.package
  vars:
    package_name: telegram-desktop
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Telegram on macOS
  community.general.homebrew_cask:
    name: telegram
    state: present
  when: ansible_os_family == 'Darwin'
