---
# tasks file for levonk.user_setup.chezmoi on Darwin (macOS)
# Copyright (c) 2025, Brillarc, LLC

- name: "Install | chezmoi (macOS)"
  block:
    - name: "Install chezmoi via vetted script installer"
      ansible.builtin.include_role:
        name: levonk.common.roles.vet_script_installer
      vars:
        vet_script_url: "https://get.chezmoi.io"
        vet_script_dest: "/tmp/chezmoi-install.sh"
        vet_script_args: ""
  become: true
