# Main task file for bitwarden-cli-support role
# This file includes OS-specific tasks for Bitwarden CLI tools (bw, bws, rbw)
# Copyright (c) 2025 the person whose account is https://github.com/levonk. Licensed under the GNU AGPL-3.0 License.
# See LICENSE file in the project root for full license information.

- name: Include OS-specific tasks for Bitwarden CLI support
  include_tasks: "{{ ansible_os_family | default('Debian') }}.yml"
  when: ansible_os_family in ['Debian', 'Windows', 'Darwin']

- name: Fail if OS is unsupported
  fail:
    msg: "Bitwarden CLI support is not implemented for this OS: {{ ansible_os_family }}"
  when: ansible_os_family not in ['Debian', 'Windows', 'Darwin']
