---
- name: "Install Visual Studio Code (macOS)"
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: "Install Visual Studio Code (Windows)"
  ansible.windows.win_winget:
    name: Microsoft.VisualStudioCode
    state: present
  when: ansible_facts['os_family'] == "Windows"

- name: "Install Visual Studio Code (Linux)"
  block:
    - name: "Add Microsoft GPG key for VS Code"
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/trusted.gpg.d/microsoft.gpg
        mode: '0644'

    - name: "Add Microsoft VS Code repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
        state: present
        filename: vscode

    - name: "Install VS Code with apt"
      ansible.builtin.apt:
        name: code
        state: present
        update_cache: true
  when: ansible_facts['os_family'] == "Debian"
