---
# tasks file for installing Claude AI Suite tools

- name: "Install @anthropic-ai/claude-code globally via npm"
  community.general.npm:
    name: "@anthropic-ai/claude-code"
    global: yes
    state: present
  become: true
  tags:
    - claude
    - claude-install

- name: "Inform user about Claude Code usage"
  ansible.builtin.debug:
    msg:
      - "Claude Code has been installed globally via npm."
      - "To use it, you must first configure it with your API key by running: claude setup"
      - "After setup, you can run the tool from your project directory with: claude"
  tags:
    - claude
    - claude-install
