---
# macOS moderate hardening tasks

- name: Enforce password policy on macOS
  ansible.builtin.command: "pwpolicy -n /Local/Default -setglobalpolicy 'minChars=16 requiresAlpha=1 requiresNumeric=1 requiresSymbol=1'"

- name: Ensure macOS firewall is enabled
  ansible.builtin.command: "/usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on"

- name: Enable macOS audit logging
  ansible.builtin.command: "/usr/bin/audit -s"
