# Chocolatey package manager configuration (Windows)
- name: Install Chocolatey
  win_powershell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force;
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  become: yes
  when: 
    - ansible_os_family == 'Windows' 
    - not chocolatey_is_installed | bool
  tags: ['packages', 'chocolatey', 'windows']

- name: Set chocolatey_is_installed fact
  set_fact:
    chocolatey_is_installed: true
  when: 
    - ansible_os_family == 'Windows' 
    - not chocolatey_is_installed | bool
  tags: ['packages', 'chocolatey', 'windows']

- name: Ensure Chocolatey is in the PATH
  win_path:
    elements: "C:\\ProgramData\\chocolatey\\bin"
  become: yes
  when: ansible_os_family == 'Windows'
  tags: ['packages', 'chocolatey', 'windows']

- name: Set cache file path (match levonk.common.package)
  set_fact:
    levonk_package_cache_file: "{{ levonk_package_cache_file | default('C:/Windows/Temp/levonk_package_cache.json') }}"

- name: Stat cache file
  win_stat:
    path: "{{ levonk_package_cache_file }}"
  register: cache_stat

- name: Slurp cache file if exists
  win_slurp:
    src: "{{ levonk_package_cache_file }}"
  register: cache_content
  when: cache_stat.stat.exists

- name: Parse cache file (if exists)
  set_fact:
    levonk_package_cache: "{{ cache_content.content | b64decode | from_json }}"
  when: cache_stat.stat.exists

- name: Determine if choco update is needed
  set_fact:
    choco_update_needed: >-
      {{
        (not cache_stat.stat.exists) or
        (levonk_package_cache is not defined) or
        ((ansible_date_time.epoch | int) - (levonk_package_cache.choco_last_update | default(0) | int) > (levonk_package_cache_expiry_minutes | default(60) | int) * 60)
      }}

- name: Update Chocolatey cache if needed
  win_shell: choco upgrade chocolatey -y
  become: yes
  when:
    - ansible_os_family == 'Windows'
    - choco_update_needed | bool
  tags: ['packages', 'chocolatey', 'windows']

- name: Update cache file timestamp after choco update
  win_copy:
    dest: "{{ levonk_package_cache_file }}"
    content: "{{ levonk_package_cache | default({}) | combine({'choco_last_update': ansible_date_time.epoch | int}) | to_nice_json }}"
  when:
    - ansible_os_family == 'Windows'
    - choco_update_needed | bool
  tags: ['packages', 'chocolatey', 'windows']

# TODO: Compliance - Ensure cache file is reviewed for security and compliance
