# YUM package manager configuration (RHEL/CentOS/Fedora)
# TODO: Compliance - Ensure cache file is reviewed for security and compliance

- name: Set cache file path (match levonk.common.package)
  set_fact:
    levonk_package_cache_file: "{{ levonk_package_cache_file | default('/var/tmp/levonk_package_cache.json') }}"

- name: Stat cache file
  stat:
    path: "{{ levonk_package_cache_file }}"
  register: cache_stat

- name: Slurp cache file if exists
  slurp:
    src: "{{ levonk_package_cache_file }}"
  register: cache_content
  when: cache_stat.stat.exists

- name: Parse cache file (if exists)
  set_fact:
    levonk_package_cache: "{{ cache_content.content | b64decode | from_json }}"
  when: cache_stat.stat.exists

- name: Determine if yum update is needed
  set_fact:
    yum_update_needed: >-
      {{
        (not cache_stat.stat.exists) or
        (levonk_package_cache is not defined) or
        ((ansible_date_time.epoch | int) - (levonk_package_cache.yum_last_update | default(0) | int) > (levonk_package_cache_expiry_minutes | default(60) | int) * 60)
      }}

- name: Update YUM cache if needed
  yum:
    update_cache: yes
  when:
    - ansible_os_family == 'RedHat'
    - yum_update_needed | bool
  tags: ['packages', 'yum', 'rhel', 'centos', 'fedora']

- name: Update cache file timestamp after yum update
  copy:
    dest: "{{ levonk_package_cache_file }}"
    content: "{{ levonk_package_cache | default({}) | combine({'yum_last_update': ansible_date_time.epoch | int}) | to_nice_json }}"
    mode: '0644'
  when:
    - ansible_os_family == 'RedHat'
    - yum_update_needed | bool
  tags: ['packages', 'yum', 'rhel', 'centos', 'fedora']
