---
# tasks file for levonk.vibeops.devops - Docker Desktop

- name: Install Docker Desktop
  levonk.common.package:
    name: docker-desktop
    state: latest
  when: "'graphical' in ansible_run_tags"
  tags:
    - devops
    - docker
    - docker-desktop
