---
# tasks file for levonk.vibeops.devops - Docker Desktop

- name: Install Docker Desktop via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - docker-desktop
    state: latest
  when: "'graphical' in ansible_run_tags"
  tags:
    - devops
    - docker
    - docker-desktop

# If there are additional repo or dependency steps for Debian, keep those as a separate block before this install.
        state: directory
        mode: '0755'

    - name: Add Docker GPG apt Key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker Desktop
      ansible.builtin.apt:
        name: docker-desktop
        state: present
        update_cache: true
