---
# Bash + Bash-it + Starship
- block:
    - name: Install bash and starship via levonk.common.package
      become: true
      levonk.common.package:
        name:
          - bash
          - starship
        state: latest
      tags:
        - thick-shell
        - bash
        - starship

    - name: Securely install Bash-it (vetted)
      include_role:
        name: levonk.common.roles.vet_script_installer
      vars:
        vet_script_url: "https://raw.githubusercontent.com/Bash-it/bash-it/master/install.sh"
        vet_script_dest: "/tmp/bash-it-install.sh"
        vet_script_args: "--silent"
      when: ansible_system != 'Windows'
      tags:
        - thick-shell
        - bash-it

  name: Bash Shell Stack
  become: true
