---
# Zsh + Oh My Zsh + PowerLevel10k (default)
- block:
    - name: Install zsh
      become: true
      ansible.builtin.package:
        name: zsh
        state: present

    - name: Securely install Oh My Zsh (vetted)
      include_role:
        name: levonk.common.roles.vet_script_installer
      vars:
        vet_script_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        vet_script_dest: "/tmp/ohmyzsh-install.sh"
        vet_script_args: "--unattended"
      when: ansible_system != 'Windows'

    - name: Install PowerLevel10k theme
      become: true
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        version: master
      when: ansible_system != 'Windows'
  name: Zsh Shell Stack
  become: true
