---
- name: Ensure backup directory exists
  win_file:
    path: C:\\backup
    state: directory

- name: Back up HKLM registry hive
  win_command: reg export HKLM C:\\backup\\HKLM.reg /y
  args:
    creates: C:\\backup\\HKLM.reg

# Step 1: Check for registry backup tool
- import_tasks: reg_backup_tool_check.yml
  tags: ['windows', 'registry', 'backup', 'check']

# Step 2: Run registry backup tasks
- import_tasks: registry_backup.yml
  tags: ['windows', 'registry', 'backup']

- name: Install Chocolatey if not present
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  args:
    creates: C:\\ProgramData\\chocolatey\\bin\\choco.exe

- name: Install WinGet - Windows package manager
  win_chocolatey:
    name: winget
    state: present
  when: base_system_install_winget | default(true)
  tags:
    - base_system
    - windows
    - winget
    - package_manager

# Configure default Windows application install paths
- import_tasks: windows/app-paths.yml
  tags:
    - windows
    - apps
    - paths

- name: Install essential packages on Windows
  win_chocolatey:
    name: "{{ base_system_packages }}"
    state: present
