---
# Baseline Windows automatic security updates

- name: Enable automatic Windows Updates (auto-install important updates)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: AUOptions
    data: 4
    type: dword
    state: present
  tags:
    - harden_baseline
    - windows
    - updates
    - security
