---
# tasks file for levonk.vibeops.knowledge - Obsidian

- name: Install Obsidian on Windows via levonk.common.package
  levonk.common.package:
    name:
      - obsidian
    state: latest
  when:
    - ansible_os_family == 'Windows'
    - 'graphical' in ansible_run_tags

- name: Install Obsidian on macOS via levonk.common.package
  levonk.common.package:
    name:
      - obsidian
    state: latest
  when:
    - ansible_os_family == 'Darwin'
    - 'graphical' in ansible_run_tags

- name: Install Obsidian on Debian-based systems
  become: true
  when:
    - ansible_os_family == 'Debian'
    - 'graphical' in ansible_run_tags
  block:
    - name: Get latest Obsidian release information
      ansible.builtin.uri:
        url: "https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest"
        return_content: true
      register: obsidian_latest_release

    - name: Find .deb asset URL from release information
      ansible.builtin.set_fact:
        obsidian_deb_url: "{{ (obsidian_latest_release.json.assets | selectattr('name', 'match', '.*\\.deb$') | list | first).browser_download_url }}"

    - name: Install Obsidian from .deb URL
      ansible.builtin.apt:
        deb: "{{ obsidian_deb_url }}"
        state: latest
      when: obsidian_deb_url is defined
