---
# tasks file for installing super-linter

- name: Install Super-Linter
  block:
    - name: Try to install Super-Linter via levonk.common.package
      levonk.common.package:
        name:
          - super-linter
        state: latest
      register: super_linter_pkg_result
      failed_when: false
      tags:
        - developer
        - tools
        - linter

    - name: Fallback to install Super-Linter via npm
      community.general.npm:
        name: super-linter
        global: yes
        state: present
      become: true
      when: super_linter_pkg_result is failed
      tags:
        - developer
        - tools
        - linter
        - fallback
