---
# tasks file for levonk.vibeops.developer - Install yq YAML processor

- name: Install yq via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - yq
    state: latest
  tags:
    - developer
    - tools
    - yq
    - yaml


- name: Verify yq installation
  ansible.builtin.command:
    cmd: yq --version
  register: yq_version
  changed_when: false
  failed_when: false
  tags:
    - developer
    - tools
    - yq
    - yaml
    - verify

- name: Display yq version
  ansible.builtin.debug:
    msg: "yq version: {{ yq_version.stdout }}"
  when: yq_version.rc == 0
  tags:
    - developer
    - tools
    - yq
    - yaml
    - verify
