# vet_script_installer/tasks/vet-dependencies.yml
# Ensures vet dependencies (shellcheck, bat) are present on all platforms for full vetting.

- name: Ensure shellcheck and bat are installed (all platforms)
  include_role:
    name: levonk.common.package
  vars:
    package_name:
      - shellcheck
      - bat
    package_state: latest
  become: yes
  tags: [vet, dependencies]
  # TODO: Compliance - Ensure vet dependencies are reviewed for compliance
