---
# Paranoid hardening: always apply moderate first, then only advanced/paranoid controls

- name: Apply moderate hardening before paranoid
  import_role:
    name: harden_moderate

# Only include advanced/paranoid-specific controls below
- name: Include Linux advanced compliance tasks
  import_tasks: linux_advanced_compliance.yml
  when: ansible_facts['os_family'] in ['Debian', 'RedHat']

- name: Include macOS advanced compliance tasks
  import_tasks: macos_advanced_compliance.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Include Windows advanced compliance tasks
  import_tasks: windows_advanced_compliance.yml
  when: ansible_facts['os_family'] == 'Windows'
