---
# Install Neovim cross-platform

- name: Install Neovim via levonk.common.package (cross-platform)
  levonk.common.package:
    name:
      - neovim
    state: latest
  tags:
    - thick-shell
    - tools
    - neovim
    - editor

- name: Ensure Neovim config directory exists
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: directory
    mode: '0755'

- name: Install lazy.nvim plugin manager
  ansible.builtin.git:
    repo: https://github.com/folke/lazy.nvim.git
    dest: "~/.config/nvim/lazy/lazy.nvim"
    version: stable
    update: no
  register: lazy_nvim_clone

- name: Display lazy.nvim install status
  ansible.builtin.debug:
    msg: "lazy.nvim plugin manager is present at ~/.config/nvim/lazy/lazy.nvim (changed={{ lazy_nvim_clone.changed }})"
