---
# tasks file for levonk.user_setup.thick-shell - zoxide

- name: Install zoxide on Windows via Chocolatey
  ansible.windows.win_chocolatey:
    name: zoxide
    state: present
  when: ansible_os_family == 'Windows'
  become: true
  tags:
    - thick-shell
    - tools
    - zoxide
    - navigation

- name: Install zoxide on Debian-based systems
  ansible.builtin.apt:
    name: zoxide
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true
  tags:
    - thick-shell
    - tools
    - zoxide
    - navigation

- name: Install zoxide on macOS via Homebrew
  community.general.homebrew:
    name: zoxide
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - thick-shell
    - tools
    - zoxide
    - navigation

- name: Verify zoxide installation
  ansible.builtin.command:
    cmd: zoxide --version
  register: zoxide_version
  changed_when: false
  failed_when: false
  tags:
    - thick-shell
    - tools
    - zoxide
    - verify

- name: Display zoxide version
  ansible.builtin.debug:
    msg: "zoxide version: {{ zoxide_version.stdout }}"
  when: zoxide_version.rc == 0
  tags:
    - thick-shell
    - tools
    - zoxide
    - verify

- name: Add zoxide init to bash
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'eval "$(zoxide init bash)"'
    create: true
  when: 
    - ansible_os_family != 'Windows'
    - "'bash' in thick_shells"
    - zoxide_version.rc == 0
  become: false
  tags:
    - thick-shell
    - tools
    - zoxide
    - integration

- name: Add zoxide init to zsh
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'eval "$(zoxide init zsh)"'
    create: true
  when: 
    - ansible_os_family != 'Windows'
    - "'zsh' in thick_shells"
    - zoxide_version.rc == 0
  become: false
  tags:
    - thick-shell
    - tools
    - zoxide
    - integration

- name: Add zoxide init to fish
  ansible.builtin.lineinfile:
    path: ~/.config/fish/config.fish
    line: 'zoxide init fish | source'
    create: true
  when: 
    - ansible_os_family != 'Windows'
    - "'fish' in thick_shells"
    - zoxide_version.rc == 0
  become: false
  tags:
    - thick-shell
    - tools
    - zoxide
    - integration
