---
- name: "Install Google Cloud SDK (macOS)"
  community.general.homebrew_cask:
    name: google-cloud-sdk
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: "Install Google Cloud SDK (Windows)"
  ansible.windows.win_chocolatey:
    name: gcloudsdk
    state: present
  when: ansible_facts['os_family'] == "Windows"

- name: "Install Google Cloud SDK (Linux)"
  include_role:
    name: levonk.common.package
  vars:
    package_name: google-cloud-sdk
    state: present
    apt_keys:
      - url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        id: google-cloud-sdk.gpg
    apt_repositories:
      - repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
  when: ansible_facts['os_family'] == "Debian"
