# .github/workflows/ansible-ci.yml

name: Ansible Role CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  molecule:
    name: Molecule Test - ${{ matrix.role.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - name: dev-ai-assisted
            path: levonk/vibeops/roles/dev-ai-assisted
          # - name: dev-ansible
          #   path: levonk/vibeops/roles/dev-ansible
          # - name: dev-general
          #   path: levonk/vibeops/roles/dev-general
          # - name: dev-python
          #   path: levonk/vibeops/roles/dev-python
          - name: chezmoi
            path: levonk/user_setup/roles/chezmoi
          - name: wsl_setup
            path: levonk/vibeops/roles/wsl_setup
          - name: devops
            path: levonk/vibeops/roles/devops

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and Molecule dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint molecule molecule-plugins[docker] docker

      - name: Run Molecule tests for ${{ matrix.role.name }}
        run: |
          cd ${{ matrix.role.path }}
          molecule test
