# .github/workflows/ansible-ci.yml

name: Ansible Role CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  molecule:
    name: Molecule Test - ${{ matrix.role }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - dev-ai-assisted
          # - dev-ansible
          # - dev-general
          # - dev-python

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and Molecule dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint molecule molecule-plugins[docker] docker

      - name: Run Molecule tests for ${{ matrix.role }}
        run: |
          cd levonk/vibeops/roles/${{ matrix.role }}
          molecule test
